kind: pipeline
name: default

clone:
  depth: 10

steps:

- name: Github Mirror
  image: alpine/git
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - git push --mirror https://cdoco:$GITHUB_TOKEN@github.com/cdoco/ua-http.git

- name: docker-release
  image: plugins/docker:18.09
  settings:
    username: drone
    password:
      from_secret: HARBOR_PASSWORD
    registry: harbor.gaozihang.com
    repo: harbor.gaozihang.com/library/ua-http
    insecure: true
    debug: true
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
      - latest
  when:
    event:
      - tag

- name: deploy-ssh
  image: appleboy/drone-ssh 
  settings:
    host: 
       - 192.168.2.6
    username: root
    password:
      from_secret: HOME_PASSWORD
    port: 22
    command_timeout: 2m 
    script:
       - docker pull harbor.gaozihang.com/library/ua-http
       - cd .docker/ua-http
       - git pull
       - docker-compose up -d --force-recreate
  when:
    event:
      - tag
